#!/usr/bin/env bash

set -eu

title="Value category cheatsheet"
url=http://localhost:3000/
output=value-category-cheatsheet.pdf

wkhtmltopdf -B 0 -L 0 -R 0 -T 0 \
            -s A4 --minimum-font-size 18 \
            --zoom 2 --dpi 100 \
            --disable-smart-shrinking \
            --title "$title" \
            "$url" "$output"
