#!/usr/bin/env bash

set -eu

title="Value category cheatsheet"
url=http://localhost:3000/
output=value-category-cheatsheet.pdf

rm -f "$output"
wkhtmltopdf -B 0 -L 0 -R 0 -T 0 \
            -s A4  \
            --zoom 1 --dpi 200 \
            --disable-smart-shrinking \
            --title "$title" \
            "$url" "$output"
